//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Address
{
	public string ZipCode
	{
		get;
		set;
	}

	public string City
	{
		get;
		set;
	}

	public string StreetName
	{
		get;
		set;
	}

	public string Country
	{
		get;
		set;
	}

	public Address(string City, string Country, string StreetName, string ZipCode)
	{
        this.City = City;
        this.Country = Country;
        this.StreetName = StreetName;
        this.ZipCode = ZipCode;
	}

}

