//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class CampingSpot
{
   public CategorySpots Category { get; set; }
    public int LocationID { get; set; }

    public int SpotID { get; set; }

    public CampingSpot(CategorySpots category, int locationid, int spotID)
	{
        this.Category = category;
	    this.LocationID = locationid;
        this.SpotID = spotID;
	}

}

