//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Category
{
	public virtual decimal Price
	{
		get;
		set;
	}

	public virtual string Details
	{
		get;
		set;
	}

	public virtual string Type
	{
		get;
		set;
	}

	public Category(string Details, decimal Price, string Type)
	{
        this.Price = Price;
        this.Details = Details;
        this.Type = Type;
	}

}

