//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Oracle.DataAccess.Client;

public class DBAccount : Database
{
	public virtual bool Update(Account Account)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool Delete(Account account)
	{
        bool resultaat = false;
        string sql;
        //sql = "Select e.EVENTID, e.Naam, e.MAXPERSONEN, e.BEGINDATUM, e.EINDDATUM, l.HUISNUMMER, l.PLAATS, l.POSTCODE From Event e Inner Join Locatie l On e.LOCATIEID = l.LOCATIEID";
        //sql = "INSERT INTO LOCATIE (PLAATS, POSTCODE, HUISNUMMER) VALUES (:plaats, :postcode, :nr)";
        sql = "DELETE FROM Gebruiker WHERE RFID = :RFID";

        try
        {
            Connect();
            OracleCommand cmd = new OracleCommand(sql, connection);
            cmd.Parameters.Add(new OracleParameter("RFID", account.RFID));
            OracleDataReader reader = cmd.ExecuteReader();
            resultaat = true;
        }
        catch (OracleException e)
        {
            Console.WriteLine(e.Message);
            throw;
        }
        finally
        {
            connection.Close();
        }
        return resultaat;
	}


	public virtual void Insert()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Select()
	{
	}


    internal Account Select(string Code)
    {
        Account resultaat = null;
        string sql;
        sql = "select * from gebruiker where RFID = :rfid";
            string lastName = "";
            string name = "";
            string type = "";
            string rfid = "";
            string city = "";
            string country = "";
            string nr = "";
            string zipcode = "";
            string email = "";

        try
        {
            Connect();
            OracleCommand cmd = new OracleCommand(sql, connection);
            cmd.Parameters.Add(new OracleParameter("RFID", Code));
            OracleDataReader reader = cmd.ExecuteReader();
            if (reader.HasRows)
            {
                while (reader.Read())
                {
                    name = Convert.ToString(reader["voornaam"]);
                    lastName = Convert.ToString(reader["achternaam"]);
                    rfid = Convert.ToString(reader["rfid"]);
                    city = Convert.ToString(reader["plaats"]);
                    country = Convert.ToString(reader["Land"]);
                    nr = Convert.ToString(reader["huisnummer"]);
                    zipcode = Convert.ToString(reader["postcode"]);
                    email = Convert.ToString(reader["emailadres"]);

                    if (Convert.ToInt32(reader["isAdmin"]) > 0)
                    {
                        type = "admin";
                    }
                    else
                    {
                        type = "bezoeker";
                    }
                }
                resultaat = new Account(new Person(new Address(city, country, nr, zipcode), email, name, lastName), type, rfid);
            }
        }
        catch (OracleException e)
        {
            throw;
        }
        finally
        {
            connection.Close();
        }
        return resultaat;
    }

    internal List<Account> SelectAll()
    {
        List<Account> resultaat = new List<Account>();
        string sql;
        sql = "select * from gebruiker";
        string type = "";
        try
        {
            Connect();
            OracleCommand cmd = new OracleCommand(sql, connection);
            OracleDataReader reader = cmd.ExecuteReader();
            if (reader.HasRows)
            {
                while (reader.Read())
                {
                    string name = Convert.ToString(reader["voornaam"]);
                    string lastName = Convert.ToString(reader["achternaam"]);
                    string rfid = Convert.ToString(reader["rfid"]);
                    string city = Convert.ToString(reader["plaats"]);
                    string country = Convert.ToString(reader["Land"]);
                    string nr = Convert.ToString(reader["huisnummer"]);
                    string zipcode = Convert.ToString(reader["postcode"]);
                    string email = Convert.ToString(reader["emailadres"]);

                    if (Convert.ToInt32(reader["isAdmin"]) > 0)
                    {
                        type = "admin";
                    }
                    else
                    {
                        type = "bezoeker";
                    }

                    Account tempAccount = new Account(new Person(new Address(city, country, nr, zipcode), email, name, lastName), type, rfid);

                    resultaat.Add(tempAccount);

                }
            }
        }
        catch (OracleException e)
        {
            throw;
        }
        finally
        {
            connection.Close();
        }
        return resultaat;
    }

    
}

