//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Oracle.DataAccess.Client;

public class DBAddress : Database
{
    
	public virtual void Update()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool Insert(Address address)
	{
	    bool resultaat = false;
        string sql;
        //sql = "Select e.EVENTID, e.Naam, e.MAXPERSONEN, e.BEGINDATUM, e.EINDDATUM, l.HUISNUMMER, l.PLAATS, l.POSTCODE From Event e Inner Join Locatie l On e.LOCATIEID = l.LOCATIEID";
	    sql = "INSERT INTO LOCATIE (PLAATS, POSTCODE, HUISNUMMER) VALUES (:plaats, :postcode, :nr)";
        try
        {
            Connect();
            OracleCommand cmd = new OracleCommand(sql, connection);
            cmd.Parameters.Add(new OracleParameter("plaats", address.City));
            cmd.Parameters.Add(new OracleParameter("postcode", address.ZipCode));
            cmd.Parameters.Add(new OracleParameter("nr", address.Number));
            cmd.ExecuteNonQuery();
            //OracleDataReader reader = cmd.ExecuteReader();
            resultaat = true;
        }
        catch (OracleException e)
        {
            
            Console.WriteLine(e.Message);
            throw;
        }
        finally
        {
            DisConnect();
        }
        return resultaat;
    }

	public virtual bool Delete(Address address )
	{
        Administation administation = new Administation();
        bool resultaat = false;
        string sql;
        //sql = "Select e.EVENTID, e.Naam, e.MAXPERSONEN, e.BEGINDATUM, e.EINDDATUM, l.HUISNUMMER, l.PLAATS, l.POSTCODE From Event e Inner Join Locatie l On e.LOCATIEID = l.LOCATIEID";
        //sql = "INSERT INTO LOCATIE (PLAATS, POSTCODE, HUISNUMMER) VALUES (:plaats, :postcode, :nr)";
	    sql = "DELETE FROM LOCATIE WHERE LOCATIEID = :AddressID";

        try
        {
            Connect();
            OracleCommand cmd = new OracleCommand(sql, connection);
            cmd.Parameters.Add(new OracleParameter("AddressID", administation.FindAddressID(address.ZipCode, address.Number)));
            OracleDataReader reader = cmd.ExecuteReader();
            resultaat = true;
        }
        catch (OracleException e)
        {
            Console.WriteLine(e.Message);
            throw;
        }
        finally
        {
            DisConnect();
        }
        return resultaat;
	}

    internal Address Select(string zipcode, string housenumber)
    {
        Administation administation = new Administation();
        Address resultaat = null;
        string sql;
        sql = "Select * From Locatie WHERE LOCATIEID = :LOCATIEID";
        string PLAATS = "";
        string POSTCODE = "";
        string HUISNUMMER = "";
        string COUNTRY = "";

        try
        {
            Connect();
            OracleCommand cmd = new OracleCommand(sql, connection);
            cmd.Parameters.Add(new OracleParameter("LOCATIEID", administation.FindAddressID(zipcode, housenumber)));
            OracleDataReader reader = cmd.ExecuteReader();
            if (reader.HasRows)
            {
                while (reader.Read())
                {
                    PLAATS = Convert.ToString(reader["PLAATS"]);
                    POSTCODE = Convert.ToString(reader["POSTCODE"]);
                    HUISNUMMER = Convert.ToString(reader["HUISNUMMER"]);

                }
                
                resultaat = new Address(PLAATS, HUISNUMMER, POSTCODE);
            }
        }
        catch (OracleException e)
        {
            throw;
        }
        finally
        {
            DisConnect();
        }
        return resultaat;
    }

    public int FindAdressID(string zipcode, string number)
    {
        
        string sql;
        sql = "Select LOCATIEID From Locatie WHERE POSTCODE = :postcode AND HUISNUMMER = :huisnummer";
        int ADRESID = -1;

        try
        {
            Connect();
            OracleCommand cmd = new OracleCommand(sql, connection);
            cmd.Parameters.Add(new OracleParameter("postcode", zipcode));
            cmd.Parameters.Add(new OracleParameter("huisnummer", number));
            OracleDataReader reader = cmd.ExecuteReader();
            if (reader.HasRows)
            {
                while (reader.Read())
                {
                    ADRESID = Convert.ToInt32(reader["LOCATIEID"]);
                }
                return ADRESID;
            }
        }
        catch (OracleException e)
        {
            throw;
        }
        finally
        {
            DisConnect();
        }
        return ADRESID;
    }
}

