//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Oracle.DataAccess.Client;

public class DBEvent : Database
{
	public virtual bool Insert(Event Event)
	{
        Administation administation = new Administation();
        bool resultaat = false;
        string sql;
        //int locatieID = administation.
        //sql = "Select e.EVENTID, e.Naam, e.MAXPERSONEN, e.BEGINDATUM, e.EINDDATUM, l.HUISNUMMER, l.PLAATS, l.POSTCODE From Event e Inner Join Locatie l On e.LOCATIEID = l.LOCATIEID";
        sql = "INSERT INTO EVENT (EVENTID, NAAM, MAXPERSONEN, BEGINDATUM, EINDDATUM, LOCATIEID) VALUES (:eventid, :naam, :maxpersonen. :begindatum, :einddatum, :locatieid)";
        try
        {
            Connect();
            OracleCommand cmd = new OracleCommand(sql, connection);
            cmd.Parameters.Add(new OracleParameter("eventid", Event.EventID));
            cmd.Parameters.Add(new OracleParameter("naam", Event.Name));
            cmd.Parameters.Add(new OracleParameter("maxpersonen", Event.MaxPerson));
            cmd.Parameters.Add(new OracleParameter("begindatum", Event.BeginTime));
            cmd.Parameters.Add(new OracleParameter("einddatum", Event.EndTime));
            cmd.Parameters.Add(new OracleParameter("locatieid", administation.FindAddressID(Event.Location.Address.ZipCode, Event.Location.Address.Number)));
            cmd.ExecuteNonQuery();
            //OracleDataReader reader = cmd.ExecuteReader();
            resultaat = true;
        }
        catch (OracleException e)
        {

            Console.WriteLine(e.Message);
            throw;
        }
        finally
        {
            DisConnect();
        }
        return resultaat;
	}

	public virtual void Select()
	{
		
	}
    /// <summary>
    /// Returned the selected Event by name
    /// </summary>
    /// <param name="EventName"></param>
    /// <returns></returns>
    public virtual Event Select(string EventName)
    {
        Event resultaat = null;
        
        string sql;
        //sql = "select * from gebruiker where RFID = :rfid";
        sql = "Select e.EVENTID, e.Naam, e.MAXPERSONEN, e.BEGINDATUM, e.EINDDATUM, l.LOCATIEID, l.HUISNUMMER, l.PLAATS, l.POSTCODE From Event e Inner Join Locatie l On e.LOCATIEID = l.LOCATIEID Where e.Naam = :name";

        int eventid = 0;
        string name = "";
        int maxpers = 0;
        string begindate = "";
        string enddate = "";
        string nr = "";
        string place = "";
        string zipcode = "";
        string country = "";

        try
        {
            Connect();
            OracleCommand cmd = new OracleCommand(sql, connection);
            cmd.Parameters.Add(new OracleParameter("Naam", name));
            OracleDataReader reader = cmd.ExecuteReader();
            if (reader.HasRows)
            {
                while (reader.Read())
                {
                    eventid = Convert.ToInt32(reader["EVENTID"]);
                    name = Convert.ToString(reader["Naam"]);
                    maxpers = Convert.ToInt32(reader["MAXPERSONEN"]);
                    begindate = Convert.ToString(reader["BEGINDATUM"]);
                    enddate = Convert.ToString(reader["EINDDATUM"]);
                    nr = Convert.ToString(reader["HUISNUMMER"]);
                    place = Convert.ToString(reader["PLAATS"]);
                    zipcode = Convert.ToString(reader["POSTCODE"]);
                }
                resultaat = new Event(new Location(new Address(country, place, nr, zipcode), name), maxpers, name, eventid, begindate, enddate);
            }
        }
        catch (OracleException e)
        {
            throw;
        }
        finally
        {
            DisConnect();
        }
        return resultaat;
    }
    /// <summary>
    /// Returned all Events in a list
    /// </summary>
    /// <returns></returns>
    public virtual List<Event> SelectAll()
    {
        List<Event> resultaat = new List<Event>();
        Event AddedEvent = null;
        string sql;
        //sql = "select * from gebruiker where RFID = :rfid";
        sql = "Select e.EVENTID, e.Naam, e.MAXPERSONEN, e.BEGINDATUM, e.EINDDATUM, l.LOCATIEID, l.HUISNUMMER, l.PLAATS, l.POSTCODE From Event e Inner Join Locatie l On e.LOCATIEID = l.LOCATIEID";

        int eventid = 0;
        string name = "";
        int maxpers = 0;
        string begindate = "";
        string enddate = "";
        string nr = "";
        string place = "";
        string zipcode = "";
        string country = "";

        try
        {
            Connect();
            OracleCommand cmd = new OracleCommand(sql, connection);
            cmd.Parameters.Add(new OracleParameter("Naam", name));
            OracleDataReader reader = cmd.ExecuteReader();
            if (reader.HasRows)
            {
                while (reader.Read()){
                    eventid = Convert.ToInt32(reader["EVENTID"]);
                    name = Convert.ToString(reader["Naam"]);
                    maxpers = Convert.ToInt32(reader["MAXPERSONEN"]);
                    begindate = Convert.ToString(reader["BEGINDATUM"]);
                    enddate = Convert.ToString(reader["EINDDATUM"]);
                    nr = Convert.ToString(reader["HUISNUMMER"]);
                    place = Convert.ToString(reader["PLAATS"]);
                    zipcode = Convert.ToString(reader["POSTCODE"]);
                    AddedEvent = new Event(new Location(new Address( country, place, nr, zipcode), name), maxpers, name, eventid, begindate, enddate);
                    resultaat.Add(AddedEvent);
                }
                return resultaat;
            }
        }
        catch (OracleException e)
        {
            throw;
        }
        finally
        {
            DisConnect();
        }
        return resultaat;
    }

	public virtual void Update(Event Event)
	{
		
	}

}

