//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class DBReserve : Database
{
	public virtual void Delete()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Inset()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Select()
	{
		throw new System.NotImplementedException();
	}

}

