//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Group
{
	public string Name
	{
		get;
		set;
	}

    public int Id { get; set; }

	public Group(string Name, int Id)
	{
        this.Name = Name;
	    this.Id = Id;
	}

}

