//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Item
{
	public string Brand
	{
		get;
		set;
	}

    public string Name { get; set; }

	public Item(string Brand)
	{
        this.Brand = Brand;
	}

    public Item(string Brand, string Name)
    {
        this.Brand = Brand;
        this.Name = Name;
    }

}

