//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Location
{
    DBAddress dbAddress = new DBAddress();
	public Address Address
	{
		get;
		set;
	}

	public string Name
	{
		get;
		set;
	}

	

	public Location(Address Address, string Name)
	{
        this.Address = Address;
        this.Name = Name;
	}

    public void AddAddress(Address address)
    {
        dbAddress.Insert(address);
    }

    public void DeleteAddress(Address address)
    {
        dbAddress.Delete(address);
    }

    public void FindAddress(string zipcode, string housenumber)
    {
        dbAddress.Select(zipcode, housenumber);
    }

    public virtual void UpdateAddress(Address address)
    {
        throw new System.NotImplementedException();
    }

}

