//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Reserve
{
	public virtual string RFID
	{
		get;
		set;
	}

	public virtual DateTime StartDate
	{
		get;
		set;
	}

	public virtual DateTime EndDate
	{
		get;
		set;
	}

	public virtual Category Category
	{
		get;
		set;
	}

	public virtual Account Account
	{
		get;
		set;
	}

    public virtual bool Paid
    {
        get;
        set;
    }

	public Reserve(Account Account, Category Category, DateTime EndDate, DateTime StartDate, string RFID, bool Paid)
	{
        this.Account = Account;
        this.Category = Category;
        this.EndDate = EndDate;
        this.StartDate = StartDate;
        this.RFID = RFID;
	}

}

