//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ReserveItem : Reserve
{
	public bool Present
	{
		get;
		set;
	}

	public Item Item
	{
		get;
		set;
	}

	public ReserveItem(Item Item, bool Present, Account Account, Category Category, DateTime EndDate, DateTime StartDate, string RFID, bool Paid) : base(Account, Category, EndDate, StartDate, RFID, Paid)
	{
        this.Item = Item;
        this.Present = Present;
	}

}

