//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ReserveSpot : Reserve
{
	public virtual bool Paid
	{
		get;
		set;
	}

	public virtual Group Group
	{
		get;
		set;
	}

	public virtual CampingSpot CampingSpot
	{
		get;
		set;
	}

	public ReserveSpot (CampingSpot CamptingSpot, Group Group, bool Paid, Account Account, Category Category, DateTime EndDate, DateTime StartDate, string RFID)
	{
        this.CampingSpot = CampingSpot;
        this.Group = Group;
        this.Paid = Paid;
	}

}

