//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Account
{
	public virtual string RFID
	{
		get;
		set;
	}

	public virtual Person Person
	{
		get;
		set;
	}

	public virtual IEnumerable<Reserve> Reserve
	{
		get;
		set;
	}

	public virtual Person Person
	{
		get;
		set;
	}

	public virtual Account(Person Person, string RFID, string Type )
	{
		throw new System.NotImplementedException();
	}

}

