//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Address
{
	public virtual string ZipCode
	{
		get;
		set;
	}

	public virtual string City
	{
		get;
		set;
	}

	public virtual string StreetName
	{
		get;
		set;
	}

	public virtual string Country
	{
		get;
		set;
	}

	public Address(string City, string Country, string StreetName, string ZipCode)
	{
	}

}

