//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Administation
{
	public virtual IEnumerable<Reserve> Reserve
	{
		get;
		set;
	}

	public virtual IEnumerable<Account> Account
	{
		get;
		set;
	}

	public virtual IEnumerable<Event> Event
	{
		get;
		set;
	}

	public virtual void Add(ICT4Event::Account Account)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Add(ICT4Event::Reserve Reserve)
	{
		throw new System.NotImplementedException();
	}

	public virtual void AddEvent(ICT4Event::Event Event)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Delete(ICT4Event::Account Account)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Delete(ICT4Event::Reserve Reserve)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Delete(ICT4Event::Event Event)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Find(ICT4Event::Account Account)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Find(ICT4Event::Event Event)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Find(ICT4Event::Reserve Reserve)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Update(ICT4Event::Account Account)
	{
		throw new System.NotImplementedException();
	}

}

