//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Event
{
	public virtual int MaxPerson
	{
		get;
		set;
	}

	public virtual ICT4Event::Location Location
	{
		get;
		set;
	}

	public virtual string Name
	{
		get;
		set;
	}

	public virtual Location Location
	{
		get;
		set;
	}

	public Event(ICT4Event::Location Location, int MaxPerson, string Name)
	{
	}

}

