//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Person
{
	public virtual Address Address
	{
		get;
		set;
	}

	public virtual string Name
	{
		get;
		set;
	}

	public virtual string LastName
	{
		get;
		set;
	}

	public virtual string Email
	{
		get;
		set;
	}

	public virtual DBAddress DBAddress
	{
		get;
		set;
	}



	public virtual Person(Address Address, string Email)
	{
        this.Address = Address;
        this.Email = Email;
	}

	public virtual void AddAddress(Address Address)
	{
		throw new System.NotImplementedException();
	}

	public virtual void DeleteAddress(Address Address)
	{
		throw new System.NotImplementedException();
	}

	public virtual void FindAddress(Address Address)
	{
		throw new System.NotImplementedException();
	}

	public virtual void UpdateAddress(Address Address)
	{
		throw new System.NotImplementedException();
	}

}

