//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Person
{
	public virtual ICT4Event::Address Address
	{
		get;
		set;
	}

	public virtual string Name
	{
		get;
		set;
	}

	public virtual string LastName
	{
		get;
		set;
	}

	public virtual string Email
	{
		get;
		set;
	}

	public virtual DBAddress DBAddress
	{
		get;
		set;
	}

	public virtual Address Address
	{
		get;
		set;
	}

	public virtual void Person(Address : Address, Email : ()
	{
		throw new System.NotImplementedException();
	}

	public virtual void AddAddress(ICT4Event::Address Address)
	{
		throw new System.NotImplementedException();
	}

	public virtual void DeleteAddress(ICT4Event::Address Address)
	{
		throw new System.NotImplementedException();
	}

	public virtual void FindAddress(ICT4Event::Address Address)
	{
		throw new System.NotImplementedException();
	}

	public virtual void UpdateAddress(ICT4Event::Address Address)
	{
		throw new System.NotImplementedException();
	}

}

