//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ReserveSpot : Reserve
{
	public virtual bool Paid
	{
		get;
		set;
	}

	public virtual Group Group
	{
		get;
		set;
	}

	public virtual CampingSpot CampingSpot
	{
		get;
		set;
	}

	public virtual void ReserveSpot (CampingSpot CampingSpot, Group Group, bool Paid)
	{
		throw new System.NotImplementedException();
	}

}

