//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ReserveItem : Reserve
{
	public virtual bool Present
	{
		get;
		set;
	}

	public virtual ICT4Event::Item Item
	{
		get;
		set;
	}

	public virtual Item Item
	{
		get;
		set;
	}

	public ReserveItem(ICT4Event::Item Item, bool Present)
	{
	}

}

